import { IEstateData } from "./app";

// mock property data - check generator.js for more details.
export const estateData: IEstateData = [
  {
    id: 44,
    price: 2211,
    apartmentName: "Honest Homes",
    image: 5,
    address: {
      streetAddress: "417 Gust Cliff",
      streetName: "Kiara Falls",
      city: "Lukasstad",
      state: "Michigan",
    },
    popular: false,
    dimension: "6x8",
    beds: 4,
    bathrooms: 4,
    propertyType: "Apartment",
    availability: "2023-04-29",
  },
  {
    id: 229,
    price: 3288,
    apartmentName: "Parkview Plaza",
    image: 3,
    address: {
      streetAddress: "32943 Bartell Plaza",
      streetName: "Thea Branch",
      city: "Gerhardborough",
      state: "Nevada",
    },
    popular: false,
    dimension: "5x7",
    beds: 1,
    bathrooms: 5,
    propertyType: "Condo",
    availability: "2022-11-24",
  },
  {
    id: 488,
    price: 2608,
    apartmentName: "United Units",
    image: 3,
    address: {
      streetAddress: "6452 Wisoky Loop",
      streetName: "Runolfsson Dam",
      city: "New Ethyl",
      state: "Illinois",
    },
    popular: false,
    dimension: "6x8",
    beds: 4,
    bathrooms: 4,
    propertyType: "Apartment",
    availability: "2023-04-29",
  },
  {
    id: 636,
    price: 4904,
    apartmentName: "Lakeview Estate",
    image: 3,
    address: {
      streetAddress: "20358 Parisian Light",
      streetName: "Fadel Valleys",
      city: "East Jaylinborough",
      state: "Nebraska",
    },
    popular: true,
    dimension: "6x8",
    beds: 2,
    bathrooms: 2,
    propertyType: "Apartment",
    availability: "2022-08-16",
  },
  {
    id: 3223213,
    price: 4559,
    apartmentName: "Vista Views",
    image: 4,
    address: {
      streetAddress: "5110 Rempel Passage",
      streetName: "Rudy Drive",
      city: "Boganchester",
      state: "New Hampshire",
    },
    popular: false,
    dimension: "9x11",
    beds: 1,
    bathrooms: 1,
    propertyType: "Condo",
    availability: "2023-01-20",
  },
  {
    id: 115,
    price: 2930,
    apartmentName: "Vista Views",
    image: 4,
    address: {
      streetAddress: "417 Gust Cliff",
      streetName: "Kiara Falls",
      city: "Lukasstad",
      state: "Michigan",
    },
    popular: true,
    dimension: "7x8",
    beds: 1,
    bathrooms: 4,
    propertyType: "Apartment",
    availability: "2022-10-20",
  },
  {
    id: 568,
    price: 2657,
    apartmentName: "United Units",
    image: 1,
    address: {
      streetAddress: "6452 Wisoky Loop",
      streetName: "Runolfsson Dam",
      city: "New Ethyl",
      state: "Illinois",
    },
    popular: true,
    dimension: "5x7",
    beds: 4,
    bathrooms: 1,
    propertyType: "Apartment",
    availability: "2022-07-14",
  },
  {
    id: 117,
    price: 4159,
    apartmentName: "Parkview Plaza",
    image: 3,
    address: {
      streetAddress: "4757 Judy Courts",
      streetName: "D'angelo Stravenue",
      city: "Port Destiney",
      state: "Missouri",
    },
    popular: true,
    dimension: "8x10",
    beds: 2,
    bathrooms: 1,
    propertyType: "House",
    availability: "2022-08-16",
  },
  {
    id: 108,
    price: 4752,
    apartmentName: "United Units",
    image: 1,
    address: {
      streetAddress: "982 Danyka Keys",
      streetName: "Mylene Isle",
      city: "Lake Avastad",
      state: "Arizona",
    },
    popular: true,
    dimension: "7x8",
    beds: 2,
    bathrooms: 5,
    propertyType: "House",
    availability: "2023-01-20",
  },
  {
    id: 66,
    price: 3844,
    apartmentName: "Parkview Plaza",
    image: 3,
    address: {
      streetAddress: "4757 Judy Courts",
      streetName: "D'angelo Stravenue",
      city: "Port Destiney",
      state: "Missouri",
    },
    popular: false,
    dimension: "7x8",
    beds: 5,
    bathrooms: 2,
    propertyType: "House",
    availability: "2023-01-20",
  },
  {
    id: 780,
    price: 3514,
    apartmentName: "Lakeview Estate",
    image: 2,
    address: {
      streetAddress: "6452 Wisoky Loop",
      streetName: "Runolfsson Dam",
      city: "New Ethyl",
      state: "Illinois",
    },
    popular: true,
    dimension: "10x12",
    beds: 2,
    bathrooms: 1,
    propertyType: "Condo",
    availability: "2022-09-16",
  },
  {
    id: 643,
    price: 241,
    apartmentName: "United Units",
    image: 4,
    address: {
      streetAddress: "20358 Parisian Light",
      streetName: "Fadel Valleys",
      city: "East Jaylinborough",
      state: "Nebraska",
    },
    popular: true,
    dimension: "8x10",
    beds: 5,
    bathrooms: 4,
    propertyType: "Townhouse",
    availability: "2023-01-20",
  },
  {
    id: 482,
    price: 2700,
    apartmentName: "Vista Views",
    image: 2,
    address: {
      streetAddress: "417 Gust Cliff",
      streetName: "Kiara Falls",
      city: "Lukasstad",
      state: "Michigan",
    },
    popular: false,
    dimension: "6x8",
    beds: 5,
    bathrooms: 4,
    propertyType: "Condo",
    availability: "2023-01-20",
  },
  {
    id: 895,
    price: 4435,
    apartmentName: "Parkview Plaza",
    image: 3,
    address: {
      streetAddress: "5110 Rempel Passage",
      streetName: "Rudy Drive",
      city: "Boganchester",
      state: "New Hampshire",
    },
    popular: true,
    dimension: "7x8",
    beds: 5,
    bathrooms: 5,
    propertyType: "House",
    availability: "2022-08-16",
  },
  {
    id: 652,
    price: 3260,
    apartmentName: "Vista Views",
    image: 4,
    address: {
      streetAddress: "4757 Judy Courts",
      streetName: "D'angelo Stravenue",
      city: "Port Destiney",
      state: "Missouri",
    },
    popular: false,
    dimension: "9x11",
    beds: 2,
    bathrooms: 1,
    propertyType: "Townhouse",
    availability: "2022-09-16",
  },
  {
    id: 53,
    price: 1734,
    apartmentName: "Lakeview Estate",
    image: 5,
    address: {
      streetAddress: "6452 Wisoky Loop",
      streetName: "Runolfsson Dam",
      city: "New Ethyl",
      state: "Illinois",
    },
    popular: false,
    dimension: "9x11",
    beds: 2,
    bathrooms: 3,
    propertyType: "Townhouse",
    availability: "2022-07-16",
  },
  {
    id: 650,
    price: 3681,
    apartmentName: "Parkview Plaza",
    image: 4,
    address: {
      streetAddress: "830 Burley Trafficway",
      streetName: "Lynch Ford",
      city: "Aldenton",
      state: "Idaho",
    },
    popular: false,
    dimension: "10x12",
    beds: 3,
    bathrooms: 2,
    propertyType: "Apartment",
    availability: "2022-10-20",
  },
  {
    id: 126,
    price: 1195,
    apartmentName: "Vista Views",
    image: 3,
    address: {
      streetAddress: "20358 Parisian Light",
      streetName: "Fadel Valleys",
      city: "East Jaylinborough",
      state: "Nebraska",
    },
    popular: true,
    dimension: "6x8",
    beds: 4,
    bathrooms: 4,
    propertyType: "Apartment",
    availability: "2022-10-20",
  },
  {
    id: 87,
    price: 4033,
    apartmentName: "Honest Homes",
    image: 5,
    address: {
      streetAddress: "982 Danyka Keys",
      streetName: "Mylene Isle",
      city: "Lake Avastad",
      state: "Arizona",
    },
    popular: false,
    dimension: "5x7",
    beds: 3,
    bathrooms: 5,
    propertyType: "House",
    availability: "2023-01-20",
  },
  {
    id: 707,
    price: 2986,
    apartmentName: "Vista Views",
    image: 3,
    address: {
      streetAddress: "368 Denesik Ports",
      streetName: "Sophia Valley",
      city: "Huldafort",
      state: "Maryland",
    },
    popular: false,
    dimension: "8x10",
    beds: 4,
    bathrooms: 2,
    propertyType: "Apartment",
    availability: "2023-01-12",
  },
  {
    id: 127,
    price: 4164,
    apartmentName: "Lakeview Estate",
    image: 5,
    address: {
      streetAddress: "5110 Rempel Passage",
      streetName: "Rudy Drive",
      city: "Boganchester",
      state: "New Hampshire",
    },
    popular: false,
    dimension: "7x8",
    beds: 5,
    bathrooms: 2,
    propertyType: "Condo",
    availability: "2022-07-14",
  },
  {
    id: 662,
    price: 686,
    apartmentName: "United Units",
    image: 3,
    address: {
      streetAddress: "20358 Parisian Light",
      streetName: "Fadel Valleys",
      city: "East Jaylinborough",
      state: "Nebraska",
    },
    popular: true,
    dimension: "6x8",
    beds: 1,
    bathrooms: 4,
    propertyType: "Condo",
    availability: "2023-04-29",
  },
  {
    id: 885,
    price: 1777,
    apartmentName: "Lakeview Estate",
    image: 5,
    address: {
      streetAddress: "94364 Delta Grove",
      streetName: "Genoveva Parkway",
      city: "Turcottestad",
      state: "Michigan",
    },
    popular: false,
    dimension: "6x8",
    beds: 4,
    bathrooms: 5,
    propertyType: "Condo",
    availability: "2022-10-20",
  },
  {
    id: 585,
    price: 3052,
    apartmentName: "United Units",
    image: 3,
    address: {
      streetAddress: "417 Gust Cliff",
      streetName: "Kiara Falls",
      city: "Lukasstad",
      state: "Michigan",
    },
    popular: false,
    dimension: "5x7",
    beds: 1,
    bathrooms: 1,
    propertyType: "House",
    availability: "2023-01-12",
  },
  {
    id: 476,
    price: 1141,
    apartmentName: "United Units",
    image: 3,
    address: {
      streetAddress: "4757 Judy Courts",
      streetName: "D'angelo Stravenue",
      city: "Port Destiney",
      state: "Missouri",
    },
    popular: true,
    dimension: "8x10",
    beds: 5,
    bathrooms: 2,
    propertyType: "Apartment",
    availability: "2022-10-20",
  },
  {
    id: 794,
    price: 4233,
    apartmentName: "Lakeview Estate",
    image: 3,
    address: {
      streetAddress: "368 Denesik Ports",
      streetName: "Sophia Valley",
      city: "Huldafort",
      state: "Maryland",
    },
    popular: false,
    dimension: "7x8",
    beds: 1,
    bathrooms: 5,
    propertyType: "Townhouse",
    availability: "2022-10-20",
  },
  {
    id: 619,
    price: 2763,
    apartmentName: "Parkview Plaza",
    image: 2,
    address: {
      streetAddress: "32943 Bartell Plaza",
      streetName: "Thea Branch",
      city: "Gerhardborough",
      state: "Nevada",
    },
    popular: true,
    dimension: "8x10",
    beds: 3,
    bathrooms: 5,
    propertyType: "Townhouse",
    availability: "2023-01-20",
  },
  {
    id: 824,
    price: 3770,
    apartmentName: "Parkview Plaza",
    image: 4,
    address: {
      streetAddress: "830 Burley Trafficway",
      streetName: "Lynch Ford",
      city: "Aldenton",
      state: "Idaho",
    },
    popular: false,
    dimension: "10x12",
    beds: 4,
    bathrooms: 2,
    propertyType: "House",
    availability: "2022-09-16",
  },
  {
    id: 632,
    price: 3329,
    apartmentName: "United Units",
    image: 2,
    address: {
      streetAddress: "982 Danyka Keys",
      streetName: "Mylene Isle",
      city: "Lake Avastad",
      state: "Arizona",
    },
    popular: false,
    dimension: "8x10",
    beds: 5,
    bathrooms: 1,
    propertyType: "Condo",
    availability: "2022-08-16",
  },
];
